## 1) Series

In [2]:
import pandas as pd
import numpy as np

In [4]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3])

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj.dtype

dtype('int64')

In [8]:
obj.shape

(4,)

In [10]:
obj2=pd.Series([4,7,-5,3], index=['d','b','c','a'])
obj2

d    4
b    7
c   -5
a    3
dtype: int64

## 2) DataFrame
DataFrame은 pd.DataFrame() 함수를 사용하여 정의한다. DataFrame

In [11]:
data = {'names': ['Hyunsuk','Hyunsuk','Hyunsuk','Charles','Charles'],
        'year': [2014, 2015, 2016, 2015, 2016],
        'points': [1.5, 1.7, 3.6, 2.4, 2.9]}
df = pd.DataFrame(data)
df

     names  year  points
0  Hyunsuk  2014     1.5
1  Hyunsuk  2015     1.7
2  Hyunsuk  2016     3.6
3  Charles  2015     2.4
4  Charles  2016     2.9

In [12]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [13]:
df.columns

Index(['names', 'year', 'points'], dtype='object')

In [14]:
df.values

array([['Hyunsuk', 2014, 1.5],
       ['Hyunsuk', 2015, 1.7],
       ['Hyunsuk', 2016, 3.6],
       ['Charles', 2015, 2.4],
       ['Charles', 2016, 2.9]], dtype=object)

In [15]:
# describe 함수
'''
DataFram df에 대하여 df.describe() 함수를 실행하게 되면,
계산이 가능한 컬럼에 한해서 각 컬럼의 평균, 분산, 최소/최대값 등 기본 통계량을 산출한 결과를 보여준다
이는 데이터셋을 DataFrame 형태로 막 읽어들인 직후에
'''

'\nDataFram df에 대하여 df.describe() 함수를 실행하게 되면,\n계산이 가능한 컬럼에 한해서 각 컬럼의 평균, 분산, 최소/최대값\n'

In [16]:
df.describe()

             year    points
count     5.00000  5.000000
mean   2015.20000  2.420000
std       0.83666  0.864292
min    2014.00000  1.500000
25%    2015.00000  1.700000
50%    2015.00000  2.400000
75%    2016.00000  2.900000
max    2016.00000  3.600000

In [17]:
df2 = pd.DataFrame(data, columns = ['year','names','points','penalty'],
                   index = ['one','two','three','four','five'])

In [19]:
df2

       year    names  points penalty
one    2014  Hyunsuk     1.5     NaN
two    2015  Hyunsuk     1.7     NaN
three  2016  Hyunsuk     3.6     NaN
four   2015  Charles     2.4     NaN
five   2016  Charles     2.9     NaN

In [20]:
df2.index

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')

In [21]:
df2.columns

Index(['year', 'names', 'points', 'penalty'], dtype='object')

In [22]:
df2.values

array([[2014, 'Hyunsuk', 1.5, nan],
       [2015, 'Hyunsuk', 1.7, nan],
       [2016, 'Hyunsuk', 3.6, nan],
       [2015, 'Charles', 2.4, nan],
       [2016, 'Charles', 2.9, nan]], dtype=object)

In [23]:
df2.describe()

             year    points
count     5.00000  5.000000
mean   2015.20000  2.420000
std       0.83666  0.864292
min    2014.00000  1.500000
25%    2015.00000  1.700000
50%    2015.00000  2.400000
75%    2016.00000  2.900000
max    2016.00000  3.600000