In [16]:
import pandas as pd
import numpy as np

In [17]:
df = pd.DataFrame(np.random.randn(6,4))
df

          0         1         2         3
0  0.264600  1.485388 -0.834790  0.325374
1 -0.427372  0.065867  1.392187  0.581695
2 -0.697996 -1.303151  0.518422  1.194600
3  1.427718  0.022964  0.135654 -0.733561
4  0.724902  0.027730  2.898456 -0.674513
5 -0.412992  0.080508 -0.862452  1.075609

In [18]:
df.columns = ['a','b','c','d']
df.index = pd.date_range('20250501', periods=6)

In [19]:
df.index

DatetimeIndex(['2025-05-01', '2025-05-02', '2025-05-03', '2025-05-04',
               '2025-05-05', '2025-05-06'],
              dtype='datetime64[ns]', freq='D')

In [20]:
df

                   a         b         c         d
2025-05-01  0.264600  1.485388 -0.834790  0.325374
2025-05-02 -0.427372  0.065867  1.392187  0.581695
2025-05-03 -0.697996 -1.303151  0.518422  1.194600
2025-05-04  1.427718  0.022964  0.135654 -0.733561
2025-05-05  0.724902  0.027730  2.898456 -0.674513
2025-05-06 -0.412992  0.080508 -0.862452  1.075609

In [21]:
df['f'] = [1.0, np.nan, 3.5, 6.1, np.nan, 7.0]
df

                   a         b         c         d    f
2025-05-01  0.264600  1.485388 -0.834790  0.325374  1.0
2025-05-02 -0.427372  0.065867  1.392187  0.581695  NaN
2025-05-03 -0.697996 -1.303151  0.518422  1.194600  3.5
2025-05-04  1.427718  0.022964  0.135654 -0.733561  6.1
2025-05-05  0.724902  0.027730  2.898456 -0.674513  NaN
2025-05-06 -0.412992  0.080508 -0.862452  1.075609  7.0

In [22]:
# NAN 제거하기
df.dropna(how='any')  # nan이 하나라도 포함된 경우 그 행을 삭제

                   a         b         c         d    f
2025-05-01  0.264600  1.485388 -0.834790  0.325374  1.0
2025-05-03 -0.697996 -1.303151  0.518422  1.194600  3.5
2025-05-04  1.427718  0.022964  0.135654 -0.733561  6.1
2025-05-06 -0.412992  0.080508 -0.862452  1.075609  7.0

In [23]:
df.dropna(how='all')

                   a         b         c         d    f
2025-05-01  0.264600  1.485388 -0.834790  0.325374  1.0
2025-05-02 -0.427372  0.065867  1.392187  0.581695  NaN
2025-05-03 -0.697996 -1.303151  0.518422  1.194600  3.5
2025-05-04  1.427718  0.022964  0.135654 -0.733561  6.1
2025-05-05  0.724902  0.027730  2.898456 -0.674513  NaN
2025-05-06 -0.412992  0.080508 -0.862452  1.075609  7.0

In [24]:
# nan 값 대체하기
df.fillna(value=5.0)

                   a         b         c         d    f
2025-05-01  0.264600  1.485388 -0.834790  0.325374  1.0
2025-05-02 -0.427372  0.065867  1.392187  0.581695  5.0
2025-05-03 -0.697996 -1.303151  0.518422  1.194600  3.5
2025-05-04  1.427718  0.022964  0.135654 -0.733561  6.1
2025-05-05  0.724902  0.027730  2.898456 -0.674513  5.0
2025-05-06 -0.412992  0.080508 -0.862452  1.075609  7.0

In [25]:
# boolean 마스크로 값을 제어하기
df.isnull()

                a      b      c      d      f
2025-05-01  False  False  False  False  False
2025-05-02  False  False  False  False   True
2025-05-03  False  False  False  False  False
2025-05-04  False  False  False  False  False
2025-05-05  False  False  False  False   True
2025-05-06  False  False  False  False  False

In [26]:
# nan이 있는 행 얻어오기
df.loc[df.isnull()['f'], :]

                   a         b         c         d   f
2025-05-02 -0.427372  0.065867  1.392187  0.581695 NaN
2025-05-05  0.724902  0.027730  2.898456 -0.674513 NaN

In [29]:
# 인덱스 기준으로 행 삭제
pd.to_datetime('20250505')

Timestamp('2025-05-05 00:00:00')

In [30]:
df.drop(pd.to_datetime('20250505'))

                   a         b         c         d    f
2025-05-01  0.264600  1.485388 -0.834790  0.325374  1.0
2025-05-02 -0.427372  0.065867  1.392187  0.581695  NaN
2025-05-03 -0.697996 -1.303151  0.518422  1.194600  3.5
2025-05-04  1.427718  0.022964  0.135654 -0.733561  6.1
2025-05-06 -0.412992  0.080508 -0.862452  1.075609  7.0

In [31]:
# 인덱스 기준으로 두 개 이상의 행 삭제하기
df.drop([pd.to_datetime('20250504'), pd.to_datetime('20250506')])

                   a         b         c         d    f
2025-05-01  0.264600  1.485388 -0.834790  0.325374  1.0
2025-05-02 -0.427372  0.065867  1.392187  0.581695  NaN
2025-05-03 -0.697996 -1.303151  0.518422  1.194600  3.5
2025-05-05  0.724902  0.027730  2.898456 -0.674513  NaN

In [32]:
# 열 삭제하기
df.drop('f', axis=1)

                   a         b         c         d
2025-05-01  0.264600  1.485388 -0.834790  0.325374
2025-05-02 -0.427372  0.065867  1.392187  0.581695
2025-05-03 -0.697996 -1.303151  0.518422  1.194600
2025-05-04  1.427718  0.022964  0.135654 -0.733561
2025-05-05  0.724902  0.027730  2.898456 -0.674513
2025-05-06 -0.412992  0.080508 -0.862452  1.075609

In [33]:
df.drop(['b', 'd'], axis=1)

                   a         c    f
2025-05-01  0.264600 -0.834790  1.0
2025-05-02 -0.427372  1.392187  NaN
2025-05-03 -0.697996  0.518422  3.5
2025-05-04  1.427718  0.135654  6.1
2025-05-05  0.724902  2.898456  NaN
2025-05-06 -0.412992 -0.862452  7.0

In [34]:
data = [[1.40, np.nan],
        [7.10, -4.5],
        [np.nan, np.nan],
        [0.75, -1.3]]

In [35]:
data

[[1.4, nan], [7.1, -4.5], [nan, nan], [0.75, -1.3]]

In [36]:
df = pd.DataFrame(data, columns = ['one','two'], index = ['a','b','c','d'])
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [37]:
# 행 방향으로 열의 합을 계산 (nan은 배제하고 계산됨)
df.sum(axis=0)

one    9.25
two   -5.80
dtype: float64

In [39]:
# 열 방향으로 각 행의 합을 계산
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [40]:
# 특정 열 또는 행의 값 계산
df['one'].sum()

np.float64(9.25)

In [41]:
df.loc['b'].sum()

np.float64(2.5999999999999996)

In [42]:
df.mean(axis=0)['two']

np.float64(-2.9)

In [43]:
df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [44]:
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [45]:
one_mean = df.mean(axis=0)['one']
two_min = df.min(axis=0)['two']

In [48]:
df['one'] = df['one'].fillna(value=one_mean)
df['two'] = df['two'].fillna(value=two_min)
df

        one  two
a  1.400000 -4.5
b  7.100000 -4.5
c  3.083333 -4.5
d  0.750000 -1.3

In [49]:
# 상관계수 구하기
df2 = pd.DataFrame(np.random.randn(6,4),
                   columns = ['a','b','c','d'],
                   index = pd.date_range('20250101', periods=6))
df2

                   a         b         c         d
2025-01-01  0.826080  0.337603  0.362369  0.028470
2025-01-02 -0.630880 -0.431546  1.161769  2.759572
2025-01-03  0.703174 -0.995746  0.381512  1.875413
2025-01-04 -0.755149  0.571447  0.972226  1.963558
2025-01-05  1.632215  0.696915  0.280121  0.624824
2025-01-06  0.822513 -1.062597  0.665895 -0.513327

In [51]:
# a열과 b열의 상관계수 산출하기 (피어슨상관계수로 계산)
df2['b'].corr(df2['c'])

np.float64(-0.10673304635363962)

In [52]:
df2.corr()

          a         b         c         d
a  1.000000  0.017855 -0.916130 -0.708043
b  0.017855  1.000000 -0.106733  0.009389
c -0.916130 -0.106733  1.000000  0.599071
d -0.708043  0.009389  0.599071  1.000000

In [53]:
# 정렬 및 기타 함수
dates = df2.index
random_dates = np.random.permutation(dates)
df2 = df2.reindex(index=random_dates, columns=['a','b','c','d'])
df2

                   a         b         c         d
2025-01-02 -0.630880 -0.431546  1.161769  2.759572
2025-01-01  0.826080  0.337603  0.362369  0.028470
2025-01-03  0.703174 -0.995746  0.381512  1.875413
2025-01-06  0.822513 -1.062597  0.665895 -0.513327
2025-01-04 -0.755149  0.571447  0.972226  1.963558
2025-01-05  1.632215  0.696915  0.280121  0.624824

In [57]:
# index 기준으로 오름차순 정렬
df2.sort_index(axis=0)

                   a         b         c         d
2025-01-01  0.826080  0.337603  0.362369  0.028470
2025-01-02 -0.630880 -0.431546  1.161769  2.759572
2025-01-03  0.703174 -0.995746  0.381512  1.875413
2025-01-04 -0.755149  0.571447  0.972226  1.963558
2025-01-05  1.632215  0.696915  0.280121  0.624824
2025-01-06  0.822513 -1.062597  0.665895 -0.513327

In [58]:
# 컬럼 기준으로 오름차순 정렬
df2.sort_index(axis=1)

                   a         b         c         d
2025-01-02 -0.630880 -0.431546  1.161769  2.759572
2025-01-01  0.826080  0.337603  0.362369  0.028470
2025-01-03  0.703174 -0.995746  0.381512  1.875413
2025-01-06  0.822513 -1.062597  0.665895 -0.513327
2025-01-04 -0.755149  0.571447  0.972226  1.963558
2025-01-05  1.632215  0.696915  0.280121  0.624824

In [62]:
# index 기준으로 내림차순 정렬
df2.sort_index(axis=0, ascending=False)

                   a         b         c         d
2025-01-06  0.822513 -1.062597  0.665895 -0.513327
2025-01-05  1.632215  0.696915  0.280121  0.624824
2025-01-04 -0.755149  0.571447  0.972226  1.963558
2025-01-03  0.703174 -0.995746  0.381512  1.875413
2025-01-02 -0.630880 -0.431546  1.161769  2.759572
2025-01-01  0.826080  0.337603  0.362369  0.028470

In [65]:
# value 기준으로 오름차순 정렬
df2.sort_values(by='a')

                   a         b         c         d
2025-01-04 -0.755149  0.571447  0.972226  1.963558
2025-01-02 -0.630880 -0.431546  1.161769  2.759572
2025-01-03  0.703174 -0.995746  0.381512  1.875413
2025-01-06  0.822513 -1.062597  0.665895 -0.513327
2025-01-01  0.826080  0.337603  0.362369  0.028470
2025-01-05  1.632215  0.696915  0.280121  0.624824

In [66]:
# value 기준으로 내림차순 정렬
df2.sort_values(by='b', ascending=False)

                   a         b         c         d
2025-01-05  1.632215  0.696915  0.280121  0.624824
2025-01-04 -0.755149  0.571447  0.972226  1.963558
2025-01-01  0.826080  0.337603  0.362369  0.028470
2025-01-02 -0.630880 -0.431546  1.161769  2.759572
2025-01-03  0.703174 -0.995746  0.381512  1.875413
2025-01-06  0.822513 -1.062597  0.665895 -0.513327

In [68]:
df2['e'] = np.random.randint(0, 6, size=6)
df2['f'] = ['alpha', 'beta', 'gamma', 'gamma', 'alpha', 'gamma']
df2

                   a         b         c         d  e      f
2025-01-02 -0.630880 -0.431546  1.161769  2.759572  5  alpha
2025-01-01  0.826080  0.337603  0.362369  0.028470  2   beta
2025-01-03  0.703174 -0.995746  0.381512  1.875413  5  gamma
2025-01-06  0.822513 -1.062597  0.665895 -0.513327  2  gamma
2025-01-04 -0.755149  0.571447  0.972226  1.963558  2  alpha
2025-01-05  1.632215  0.696915  0.280121  0.624824  0  gamma

In [69]:
df2.f.unique()

array(['alpha', 'beta', 'gamma'], dtype=object)

In [70]:
df2.f.value_counts()

f
gamma    3
alpha    2
beta     1
Name: count, dtype: int64

In [72]:
df2['f'].isin(['alpha', 'gamma'])

2025-01-02     True
2025-01-01    False
2025-01-03     True
2025-01-06     True
2025-01-04     True
2025-01-05     True
Name: f, dtype: bool

In [73]:
df2.loc[df2['f'].isin(['alpha', 'gamma']), :]

                   a         b         c         d  e      f
2025-01-02 -0.630880 -0.431546  1.161769  2.759572  5  alpha
2025-01-03  0.703174 -0.995746  0.381512  1.875413  5  gamma
2025-01-06  0.822513 -1.062597  0.665895 -0.513327  2  gamma
2025-01-04 -0.755149  0.571447  0.972226  1.963558  2  alpha
2025-01-05  1.632215  0.696915  0.280121  0.624824  0  gamma