## DataFrame 조작하기

In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.DataFrame(np.random.randn(6,4))
df

          0         1         2         3
0  0.615651  0.400427 -1.441689  1.240922
1 -0.433902  1.419840 -0.146937  0.839186
2 -0.536355 -2.861472  0.311537 -0.619679
3 -0.478387  0.272890  1.105682 -1.669019
4 -0.714056 -0.648674  1.990645 -0.520403
5 -0.082028  0.289095  1.104627 -0.121328

In [8]:
df.columns = ['a','b','c','d']
df.index = pd.date_range('20250501', periods=6)

In [9]:
df.index

DatetimeIndex(['2025-05-01', '2025-05-02', '2025-05-03', '2025-05-04',
               '2025-05-05', '2025-05-06'],
              dtype='datetime64[ns]', freq='D')

In [10]:
df

                   a         b         c         d
2025-05-01  0.615651  0.400427 -1.441689  1.240922
2025-05-02 -0.433902  1.419840 -0.146937  0.839186
2025-05-03 -0.536355 -2.861472  0.311537 -0.619679
2025-05-04 -0.478387  0.272890  1.105682 -1.669019
2025-05-05 -0.714056 -0.648674  1.990645 -0.520403
2025-05-06 -0.082028  0.289095  1.104627 -0.121328

In [11]:
df['f'] = [1.0, np.nan, 3.5, 6.1, np.nan, 7.0]
df

                   a         b         c         d    f
2025-05-01  0.615651  0.400427 -1.441689  1.240922  1.0
2025-05-02 -0.433902  1.419840 -0.146937  0.839186  NaN
2025-05-03 -0.536355 -2.861472  0.311537 -0.619679  3.5
2025-05-04 -0.478387  0.272890  1.105682 -1.669019  6.1
2025-05-05 -0.714056 -0.648674  1.990645 -0.520403  NaN
2025-05-06 -0.082028  0.289095  1.104627 -0.121328  7.0

In [12]:
# NAN 제거하기
df.dropna(how='any')  # nan이 하나라도 포함된 경우 그 행을 삭제

                   a         b         c         d    f
2025-05-01  0.615651  0.400427 -1.441689  1.240922  1.0
2025-05-03 -0.536355 -2.861472  0.311537 -0.619679  3.5
2025-05-04 -0.478387  0.272890  1.105682 -1.669019  6.1
2025-05-06 -0.082028  0.289095  1.104627 -0.121328  7.0

In [13]:
df.dropna(how='all')

                   a         b         c         d    f
2025-05-01  0.615651  0.400427 -1.441689  1.240922  1.0
2025-05-02 -0.433902  1.419840 -0.146937  0.839186  NaN
2025-05-03 -0.536355 -2.861472  0.311537 -0.619679  3.5
2025-05-04 -0.478387  0.272890  1.105682 -1.669019  6.1
2025-05-05 -0.714056 -0.648674  1.990645 -0.520403  NaN
2025-05-06 -0.082028  0.289095  1.104627 -0.121328  7.0

In [14]:
# nan 값 대체하기
df.fillna(value=5.0)

                   a         b         c         d    f
2025-05-01  0.615651  0.400427 -1.441689  1.240922  1.0
2025-05-02 -0.433902  1.419840 -0.146937  0.839186  5.0
2025-05-03 -0.536355 -2.861472  0.311537 -0.619679  3.5
2025-05-04 -0.478387  0.272890  1.105682 -1.669019  6.1
2025-05-05 -0.714056 -0.648674  1.990645 -0.520403  5.0
2025-05-06 -0.082028  0.289095  1.104627 -0.121328  7.0

In [15]:
# boolean 마스크로 값을 제어하기
df.isnull()

                a      b      c      d      f
2025-05-01  False  False  False  False  False
2025-05-02  False  False  False  False   True
2025-05-03  False  False  False  False  False
2025-05-04  False  False  False  False  False
2025-05-05  False  False  False  False   True
2025-05-06  False  False  False  False  False

In [16]:
# nan이 있는 행 얻어오기
df.loc[df.isnull()['f'], :]

                   a         b         c         d   f
2025-05-02 -0.433902  1.419840 -0.146937  0.839186 NaN
2025-05-05 -0.714056 -0.648674  1.990645 -0.520403 NaN

In [17]:
# 인덱스 기준으로 행 삭제
pd.to_datetime('20250505')

Timestamp('2025-05-05 00:00:00')

In [18]:
df.drop(pd.to_datetime('20250505'))

                   a         b         c         d    f
2025-05-01  0.615651  0.400427 -1.441689  1.240922  1.0
2025-05-02 -0.433902  1.419840 -0.146937  0.839186  NaN
2025-05-03 -0.536355 -2.861472  0.311537 -0.619679  3.5
2025-05-04 -0.478387  0.272890  1.105682 -1.669019  6.1
2025-05-06 -0.082028  0.289095  1.104627 -0.121328  7.0

In [19]:
# 인덱스 기준으로 두 개 이상의 행 삭제하기
df.drop([pd.to_datetime('20250504'), pd.to_datetime('20250506')])

                   a         b         c         d    f
2025-05-01  0.615651  0.400427 -1.441689  1.240922  1.0
2025-05-02 -0.433902  1.419840 -0.146937  0.839186  NaN
2025-05-03 -0.536355 -2.861472  0.311537 -0.619679  3.5
2025-05-05 -0.714056 -0.648674  1.990645 -0.520403  NaN

In [20]:
# 열 삭제하기
df.drop('f', axis=1)

                   a         b         c         d
2025-05-01  0.615651  0.400427 -1.441689  1.240922
2025-05-02 -0.433902  1.419840 -0.146937  0.839186
2025-05-03 -0.536355 -2.861472  0.311537 -0.619679
2025-05-04 -0.478387  0.272890  1.105682 -1.669019
2025-05-05 -0.714056 -0.648674  1.990645 -0.520403
2025-05-06 -0.082028  0.289095  1.104627 -0.121328

In [21]:
df.drop(['b', 'd'], axis=1)

                   a         c    f
2025-05-01  0.615651 -1.441689  1.0
2025-05-02 -0.433902 -0.146937  NaN
2025-05-03 -0.536355  0.311537  3.5
2025-05-04 -0.478387  1.105682  6.1
2025-05-05 -0.714056  1.990645  NaN
2025-05-06 -0.082028  1.104627  7.0

In [22]:
data = [[1.40, np.nan],
        [7.10, -4.5],
        [np.nan, np.nan],
        [0.75, -1.3]]

In [23]:
data

[[1.4, nan], [7.1, -4.5], [nan, nan], [0.75, -1.3]]

In [24]:
df = pd.DataFrame(data, columns = ['one','two'], index = ['a','b','c','d'])
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [25]:
# 행 방향으로 열의 합을 계산 (nan은 배제하고 계산됨)
df.sum(axis=0)

one    9.25
two   -5.80
dtype: float64

In [26]:
# 열 방향으로 각 행의 합을 계산
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [27]:
# 특정 열 또는 행의 값 계산
df['one'].sum()

np.float64(9.25)

In [28]:
df.loc['b'].sum()

np.float64(2.5999999999999996)

In [29]:
df.mean(axis=0)['two']

np.float64(-2.9)

In [30]:
df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [31]:
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [32]:
one_mean = df.mean(axis=0)['one']
two_min = df.min(axis=0)['two']

In [33]:
df['one'] = df['one'].fillna(value=one_mean)
df['two'] = df['two'].fillna(value=two_min)
df

        one  two
a  1.400000 -4.5
b  7.100000 -4.5
c  3.083333 -4.5
d  0.750000 -1.3

In [34]:
# 상관계수 구하기
df2 = pd.DataFrame(np.random.randn(6,4),
                   columns = ['a','b','c','d'],
                   index = pd.date_range('20250101', periods=6))
df2

                   a         b         c         d
2025-01-01 -0.729226 -1.902974 -0.011489 -0.117088
2025-01-02  0.220258 -0.184192  1.898826 -0.484660
2025-01-03  2.111081  0.796488 -0.970042 -1.713993
2025-01-04  0.632748 -0.628274 -0.679272  0.567367
2025-01-05 -0.332959 -0.199257 -1.822330  0.982194
2025-01-06  2.035530  1.965177  1.024371 -0.510645

In [35]:
# a열과 b열의 상관계수 산출하기 (피어슨상관계수로 계산)
df2['b'].corr(df2['c'])

np.float64(0.1886985605341828)

In [36]:
df2.corr()

          a         b         c         d
a  1.000000  0.870403  0.123847 -0.676419
b  0.870403  1.000000  0.188699 -0.426835
c  0.123847  0.188699  1.000000 -0.321482
d -0.676419 -0.426835 -0.321482  1.000000

In [37]:
# 정렬 및 기타 함수
dates = df2.index
random_dates = np.random.permutation(dates)
df2 = df2.reindex(index=random_dates, columns=['a','b','c','d'])
df2

                   a         b         c         d
2025-01-01 -0.729226 -1.902974 -0.011489 -0.117088
2025-01-05 -0.332959 -0.199257 -1.822330  0.982194
2025-01-03  2.111081  0.796488 -0.970042 -1.713993
2025-01-06  2.035530  1.965177  1.024371 -0.510645
2025-01-04  0.632748 -0.628274 -0.679272  0.567367
2025-01-02  0.220258 -0.184192  1.898826 -0.484660

In [38]:
# index 기준으로 오름차순 정렬
df2.sort_index(axis=0)

                   a         b         c         d
2025-01-01 -0.729226 -1.902974 -0.011489 -0.117088
2025-01-02  0.220258 -0.184192  1.898826 -0.484660
2025-01-03  2.111081  0.796488 -0.970042 -1.713993
2025-01-04  0.632748 -0.628274 -0.679272  0.567367
2025-01-05 -0.332959 -0.199257 -1.822330  0.982194
2025-01-06  2.035530  1.965177  1.024371 -0.510645

In [39]:
# 컬럼 기준으로 오름차순 정렬
df2.sort_index(axis=1)

                   a         b         c         d
2025-01-01 -0.729226 -1.902974 -0.011489 -0.117088
2025-01-05 -0.332959 -0.199257 -1.822330  0.982194
2025-01-03  2.111081  0.796488 -0.970042 -1.713993
2025-01-06  2.035530  1.965177  1.024371 -0.510645
2025-01-04  0.632748 -0.628274 -0.679272  0.567367
2025-01-02  0.220258 -0.184192  1.898826 -0.484660

In [40]:
# index 기준으로 내림차순 정렬
df2.sort_index(axis=0, ascending=False)

                   a         b         c         d
2025-01-06  2.035530  1.965177  1.024371 -0.510645
2025-01-05 -0.332959 -0.199257 -1.822330  0.982194
2025-01-04  0.632748 -0.628274 -0.679272  0.567367
2025-01-03  2.111081  0.796488 -0.970042 -1.713993
2025-01-02  0.220258 -0.184192  1.898826 -0.484660
2025-01-01 -0.729226 -1.902974 -0.011489 -0.117088

In [41]:
# value 기준으로 오름차순 정렬
df2.sort_values(by='a')

                   a         b         c         d
2025-01-01 -0.729226 -1.902974 -0.011489 -0.117088
2025-01-05 -0.332959 -0.199257 -1.822330  0.982194
2025-01-02  0.220258 -0.184192  1.898826 -0.484660
2025-01-04  0.632748 -0.628274 -0.679272  0.567367
2025-01-06  2.035530  1.965177  1.024371 -0.510645
2025-01-03  2.111081  0.796488 -0.970042 -1.713993

In [42]:
# value 기준으로 내림차순 정렬
df2.sort_values(by='b', ascending=False)

                   a         b         c         d
2025-01-06  2.035530  1.965177  1.024371 -0.510645
2025-01-03  2.111081  0.796488 -0.970042 -1.713993
2025-01-02  0.220258 -0.184192  1.898826 -0.484660
2025-01-05 -0.332959 -0.199257 -1.822330  0.982194
2025-01-04  0.632748 -0.628274 -0.679272  0.567367
2025-01-01 -0.729226 -1.902974 -0.011489 -0.117088

In [43]:
df2['e'] = np.random.randint(0, 6, size=6)
df2['f'] = ['alpha', 'beta', 'gamma', 'gamma', 'alpha', 'gamma']
df2

                   a         b         c         d  e      f
2025-01-01 -0.729226 -1.902974 -0.011489 -0.117088  1  alpha
2025-01-05 -0.332959 -0.199257 -1.822330  0.982194  3   beta
2025-01-03  2.111081  0.796488 -0.970042 -1.713993  0  gamma
2025-01-06  2.035530  1.965177  1.024371 -0.510645  1  gamma
2025-01-04  0.632748 -0.628274 -0.679272  0.567367  2  alpha
2025-01-02  0.220258 -0.184192  1.898826 -0.484660  4  gamma

In [44]:
df2.f.unique()

array(['alpha', 'beta', 'gamma'], dtype=object)

In [45]:
df2.f.value_counts()

f
gamma    3
alpha    2
beta     1
Name: count, dtype: int64

In [46]:
df2['f'].isin(['alpha', 'gamma'])

2025-01-01     True
2025-01-05    False
2025-01-03     True
2025-01-06     True
2025-01-04     True
2025-01-02     True
Name: f, dtype: bool

In [47]:
df2.loc[df2['f'].isin(['alpha', 'gamma']), :]

                   a         b         c         d  e      f
2025-01-01 -0.729226 -1.902974 -0.011489 -0.117088  1  alpha
2025-01-03  2.111081  0.796488 -0.970042 -1.713993  0  gamma
2025-01-06  2.035530  1.965177  1.024371 -0.510645  1  gamma
2025-01-04  0.632748 -0.628274 -0.679272  0.567367  2  alpha
2025-01-02  0.220258 -0.184192  1.898826 -0.484660  4  gamma

In [48]:
add = lambda x, y : x + y

In [49]:
print(add(3,5))

8

In [50]:
df3 = pd.DataFrame(np.random.randn(4,3),
                   index = ['Seoul','Incheon','Busan','Daegu'],
                   columns = ['b','d','e',])
df3

                b         d         e
Seoul    1.430538 -0.148733  2.856513
Incheon  2.599756 -0.368940  0.655249
Busan    0.220233  1.055529 -1.247170
Daegu   -0.024919 -0.809601 -0.399705

In [51]:
# x.max : 행 또는 열의 최대값, x.min : 행 또는 열의 최소값
func = lambda x: x.max() - x.min()

In [52]:
# 행 방향으로  열 별로 lambda 함수 값을 계산
df3.apply(func, axis=0)

b    2.624675
d    1.865129
e    4.103684
dtype: float64

In [53]:
# 열 방향으로 행 별로 값을 계산
df3.apply(func, axis=1)

Seoul      3.005246
Incheon    2.968696
Busan      2.302699
Daegu      0.784682
dtype: float64